trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: search
    TimeoutInMinutes: 240
    MaxParallel: 2
    # TODO: change 'Preview' cloud back to public after search RP fixes deletion metadata issue
    Clouds: 'Preview'
    SupportedClouds: 'Preview,UsGov,China'
    EnvVars:
      AZURE_SEARCH_TEST_MODE: Live
